# CLI Interface Contract for NuGet Update Bot
# OpenAPI-style specification for command-line interface

openapi: 3.0.0
info:
  title: NuGet Update Bot CLI
  version: 1.0.0
  description: Command-line interface for scanning and updating NuGet packages

paths:
  /scan:
    post:
      summary: Scan project for outdated packages
      operationId: scanCommand
      parameters:
        - name: project
          in: query
          required: true
          description: Path to .csproj file or directory
          schema:
            type: string
            pattern: '^.+\.(cs|fs|vb)proj$|^.+/$'
        - name: include-prerelease
          in: query
          required: false
          description: Include pre-release versions in scan
          schema:
            type: boolean
            default: false
        - name: verbose
          in: query
          required: false
          description: Enable verbose output
          schema:
            type: boolean
            default: false
        - name: no-cache
          in: query
          required: false
          description: Bypass cache and fetch fresh data
          schema:
            type: boolean
            default: false
      responses:
        '0':
          description: Success - scan completed
          content:
            text/plain:
              schema:
                type: string
                example: |
                  Found 3 outdated packages:
                  Newtonsoft.Json  12.0.3 → 13.0.3
                  Serilog          2.10.0 → 3.1.1
        '3':
          description: File not found
          content:
            text/plain:
              schema:
                type: string
                example: "Error: Project file not found: /path/to/project.csproj"
        '4':
          description: Network error
          content:
            text/plain:
              schema:
                type: string
                example: "Network error: Unable to connect to NuGet.org"

  /update:
    post:
      summary: Update outdated packages
      operationId: updateCommand
      parameters:
        - name: project
          in: query
          required: true
          description: Path to .csproj file or directory
          schema:
            type: string
        - name: dry-run
          in: query
          required: false
          description: Preview changes without applying them
          schema:
            type: boolean
            default: false
        - name: exclude
          in: query
          required: false
          description: Package names to exclude from updates
          schema:
            type: array
            items:
              type: string
          style: form
          explode: true
        - name: policy
          in: query
          required: false
          description: Update policy (patch, minor, major)
          schema:
            type: string
            enum: [patch, minor, major]
            default: minor
        - name: verbose
          in: query
          required: false
          description: Enable verbose output
          schema:
            type: boolean
            default: false
      responses:
        '0':
          description: Success - updates applied
          content:
            text/plain:
              schema:
                type: string
                example: "Successfully updated 3 packages"
        '1':
          description: General error
        '3':
          description: File not found
        '5':
          description: Parse error - malformed project file

  /report:
    post:
      summary: Generate update report
      operationId: reportCommand
      parameters:
        - name: project
          in: query
          required: true
          description: Path to .csproj file or directory
          schema:
            type: string
        - name: format
          in: query
          required: false
          description: Output format
          schema:
            type: string
            enum: [console, json]
            default: console
        - name: output
          in: query
          required: false
          description: Output file path (stdout if not specified)
          schema:
            type: string
        - name: include-up-to-date
          in: query
          required: false
          description: Include packages that are already up-to-date
          schema:
            type: boolean
            default: false
      responses:
        '0':
          description: Success - report generated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateReport'
            text/plain:
              schema:
                type: string

components:
  schemas:
    UpdateReport:
      type: object
      required:
        - generatedAt
        - projectPath
        - outdatedPackages
        - summary
      properties:
        generatedAt:
          type: string
          format: date-time
          example: "2025-11-13T10:00:00Z"
        projectPath:
          type: string
          example: "/path/to/project.csproj"
        outdatedPackages:
          type: array
          items:
            $ref: '#/components/schemas/PackageUpdate'
        summary:
          $ref: '#/components/schemas/UpdateSummary'

    PackageUpdate:
      type: object
      required:
        - name
        - currentVersion
        - latestVersion
        - updateType
      properties:
        name:
          type: string
          example: "Newtonsoft.Json"
        currentVersion:
          type: string
          example: "12.0.3"
        latestVersion:
          type: string
          example: "13.0.3"
        updateType:
          type: string
          enum: [patch, minor, major, prerelease]
          example: "major"
        isDeprecated:
          type: boolean
          default: false

    UpdateSummary:
      type: object
      required:
        - totalPackages
        - outdatedCount
      properties:
        totalPackages:
          type: integer
          example: 15
        outdatedCount:
          type: integer
          example: 3
        majorUpdates:
          type: integer
          example: 1
        minorUpdates:
          type: integer
          example: 1
        patchUpdates:
          type: integer
          example: 1
        excludedCount:
          type: integer
          example: 0

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          example: "FILE_NOT_FOUND"
        message:
          type: string
          example: "Project file not found at specified path"
        details:
          type: string
          example: "Please verify the file path and try again"

  parameters:
    ProjectPath:
      name: project
      in: query
      required: true
      description: Path to .csproj, .fsproj, .vbproj file or directory containing project files
      schema:
        type: string
        minLength: 1

    VerboseFlag:
      name: verbose
      in: query
      required: false
      description: Enable verbose diagnostic output
      schema:
        type: boolean
        default: false

# Exit Codes
x-exit-codes:
  - code: 0
    description: Success - operation completed successfully
  - code: 1
    description: General error - unexpected failure
  - code: 2
    description: Invalid arguments - command line parsing error
  - code: 3
    description: File not found - project file does not exist
  - code: 4
    description: Network error - unable to connect to NuGet.org
  - code: 5
    description: Parse error - malformed project file

# Command Examples
x-command-examples:
  scan:
    - description: Basic scan
      command: nuget-update-bot scan --project ./MyApp.csproj
    - description: Scan with prerelease
      command: nuget-update-bot scan --project ./MyApp.csproj --include-prerelease
    - description: Scan directory
      command: nuget-update-bot scan --project ./src/

  update:
    - description: Dry run update
      command: nuget-update-bot update --project ./MyApp.csproj --dry-run
    - description: Update with exclusions
      command: nuget-update-bot update --project ./MyApp.csproj --exclude Legacy.Package Old.Library
    - description: Update patches only
      command: nuget-update-bot update --project ./MyApp.csproj --policy patch

  report:
    - description: Generate JSON report
      command: nuget-update-bot report --project ./MyApp.csproj --format json
    - description: Save report to file
      command: nuget-update-bot report --project ./MyApp.csproj --format json --output report.json