# Copy this file to .github/workflows/update-nuget-packages.yml in your target repository
# For LoadSurge: Use schedule cron '0 9 * * 6' (Saturday)
# For xUnitV3LoadFramework: Use schedule cron '0 9 * * 1' (Monday)

name: Update NuGet Packages

on:
  schedule:
    - cron: '0 9 * * 1'  # Change this: 1=Monday, 6=Saturday
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  update-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install NugetUpdateBot
        run: |
          dotnet tool install --global NugetUpdateBot || dotnet tool update --global NugetUpdateBot

      - name: Find .csproj files
        id: find-projects
        run: |
          PROJECTS=$(find . -name "*.csproj" | head -1)
          echo "Found project: $PROJECTS"
          echo "project=$PROJECTS" >> $GITHUB_OUTPUT

      - name: Scan for updates
        id: scan
        run: |
          if [ -n "${{ steps.find-projects.outputs.project }}" ]; then
            nuget-update-bot scan "${{ steps.find-projects.outputs.project }}" --verbose
            SCAN_EXIT=$?
            echo "scan_exit=$SCAN_EXIT" >> $GITHUB_OUTPUT

            if [ $SCAN_EXIT -eq 1 ]; then
              echo "updates_available=true" >> $GITHUB_OUTPUT
            else
              echo "updates_available=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "No .csproj files found"
            exit 1
          fi

      - name: Create update branch
        if: steps.scan.outputs.updates_available == 'true'
        run: |
          BRANCH_NAME="nuget-updates-$(date +%Y%m%d)"
          git checkout -b "$BRANCH_NAME"
          echo "branch=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Update packages
        if: steps.scan.outputs.updates_available == 'true'
        run: |
          for project in $(find . -name "*.csproj"); do
            echo "Updating $project..."
            nuget-update-bot update "$project" --verbose || true
          done

      - name: Configure Git
        if: steps.scan.outputs.updates_available == 'true'
        run: |
          git config user.name "NuGet Update Bot"
          git config user.email "nuget-bot@github-actions"

      - name: Commit changes
        if: steps.scan.outputs.updates_available == 'true'
        id: commit
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            COMMIT_MSG="chore: update NuGet packages

          Automated NuGet package updates by NugetUpdateBot

          Generated on: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
            git commit -m "$COMMIT_MSG"
            git push origin "${{ env.branch }}"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.scan.outputs.updates_available == 'true' && steps.commit.outputs.has_changes == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "🔄 Update NuGet Packages" \
            --body "## NuGet Package Updates

          This PR contains automatic NuGet package updates generated by NugetUpdateBot.

          ### Changes
          - Updated outdated NuGet packages to their latest versions
          - All updates follow semantic versioning best practices

          ### Testing
          Please review the changes and ensure:
          - [ ] All tests pass
          - [ ] No breaking changes introduced
          - [ ] Application builds successfully

          ### Generated Information
          - **Date**: $(date -u +'%Y-%m-%d %H:%M:%S UTC')
          - **Triggered by**: GitHub Actions (Scheduled)

          ---
          🤖 This PR was automatically created by [NugetUpdateBot](https://github.com/mrviduus/nuget-update-bot)" \
            --base main \
            --head "${{ env.branch }}"

      - name: No updates needed
        if: steps.scan.outputs.updates_available == 'false'
        run: |
          echo "✅ All packages are up to date!"
